# Generated by Django 4.2 on 2026-02-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=3000)),
                ('gender', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='predict_water_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.CharField(max_length=300)),
                ('Name_of_Monitoring_Location', models.CharField(max_length=300)),
                ('Type_Water_Body', models.CharField(max_length=300)),
                ('State_Name', models.CharField(max_length=300)),
                ('Temperature', models.CharField(max_length=300)),
                ('Dissolved_Oxygen_mgperL', models.CharField(max_length=300)),
                ('pH', models.CharField(max_length=300)),
                ('Conductivity_mhospercm', models.CharField(max_length=300)),
                ('BOD_mgperL', models.CharField(max_length=300)),
                ('NitrateN_NitriteN_mgperL', models.CharField(max_length=300)),
                ('Fecal_Coliform_MPNper100ml', models.CharField(max_length=300)),
                ('Total_Coliform_MPNper100ml', models.CharField(max_length=300)),
                ('Prediction', models.CharField(max_length=300)),
            ],
        ),
    ]
